spring:
  datasource:
    url:jdbc:mysql://localhost:3306:sampale?createDatabaseIfNotExist=true
    username:root
    password:
    driver-class-name:com.mysql.jdbc.driver
  jpa:
    hibernate:
      naming:
        physical-strategy:org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
